// Timeline audio (T-161): import a song generated by the test into the
// TIMELINE workspace, see its waveform, set the offset and volume, play
// with it, and get a clear refusal for a damaged file. The test studio runs
// with --no-audio, so nothing is played on the Mac's speakers: the song's
// clock (native playback) is covered by the unit tests; here the timeline
// runs on the system clock. No third-party audio file anywhere.
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { test, expect, useStudio, openUi, openWorkspace } from '../studio';

const studio = useStudio();

/** A 16-bit mono WAV of a sine: `amp` 0..1, `seconds` long. */
function sineWav(seconds: number, amp: number, rate = 22_050, hz = 440): Buffer {
  const n = Math.round(seconds * rate);
  const b = Buffer.alloc(44 + 2 * n);
  b.write('RIFF', 0); b.writeUInt32LE(36 + 2 * n, 4); b.write('WAVE', 8);
  b.write('fmt ', 12); b.writeUInt32LE(16, 16); b.writeUInt16LE(1, 20); b.writeUInt16LE(1, 22);
  b.writeUInt32LE(rate, 24); b.writeUInt32LE(rate * 2, 28); b.writeUInt16LE(2, 32); b.writeUInt16LE(16, 34);
  b.write('data', 36); b.writeUInt32LE(2 * n, 40);
  for (let i = 0; i < n; i++) b.writeInt16LE(Math.round(amp * 32767 * Math.sin(2 * Math.PI * hz * i / rate)), 44 + 2 * i);
  return b;
}

interface Song { file: string; offset_s: number; gain: number; duration_s: number }
const timeline = async () => studio.get<{ state: { name: string | null; length: number; position: number; playing: boolean; audio: Song | null }; show: { audio: Song | null } | null; audio: { state: string; clock: string } }>('/api/timeline');

test.beforeAll(async () => {
  const cue = (await studio.presets()).presets[0].id;
  const show = (name: string, time_base: string) => ({
    name, time_base,
    tracks: [{ name: 'Piste 1', layer: 1, events: [{ id: 1, start: 0, len: 2, source: { kind: 'cue', id: cue } }] }],
  });
  expect(await studio.post('/api/shows', show('Chanson e2e', 'seconds'))).toBe(200);
  expect(await studio.post('/api/shows', show('Phrase e2e', 'beats'))).toBe(200);
});

test.beforeEach(async ({ page }) => {
  await studio.post('/api/timeline/stop');
  await studio.reset();
  await openUi(page, studio);
  await openWorkspace(page, 'timeline');
});

test('import a generated song: waveform, offset, volume, saved with the show, playback', async ({ page }) => {
  await page.locator('#tlShow').selectOption('Chanson e2e');
  await expect.poll(async () => (await timeline()).state.name).toBe('Chanson e2e');
  await expect(page.locator('#tlWaveEmpty')).toBeVisible();
  await expect(page.locator('#tlOffset')).toBeDisabled();

  // 3 s sine of amplitude 0.5, made by the test.
  await page.locator('#tlImportFile').setInputFiles({ name: 'Sinus e2e.wav', mimeType: 'audio/wav', buffer: sineWav(3, 0.5) });
  await expect(page.locator('#tlMsg')).toContainText('« Sinus e2e.wav » (0:03.0) ajouté au show');
  let t = await timeline();
  expect(t.state.audio).toMatchObject({ file: 'Sinus e2e.wav', offset_s: 0, gain: 1, duration_s: 3 });
  expect(t.state.length).toBe(3); // the show lasts until the song ends (events: 2 s)
  expect(t.audio.state).toBe('disabled');
  await expect(page.locator('#tlSong')).toHaveValue('Sinus e2e.wav');
  await expect(page.locator('#tlSongStatus')).toContainText('lecture audio désactivée');

  // Stored in media/audio/ of the data dir, and only there.
  const media = path.join(studio.dataDir, 'media', 'audio');
  expect(readdirSync(media).filter(f => !f.startsWith('.'))).toEqual(['Sinus e2e.wav']);

  // The waveform: peaks at ≈ 0.5, drawn on the canvas.
  const wave = await studio.get<{ max: number[]; min: number[]; to: number }>('/api/timeline/waveform?px=30');
  expect(wave.to).toBe(3);
  expect(Math.max(...wave.max)).toBeCloseTo(0.5, 2);
  expect(Math.min(...wave.min)).toBeCloseTo(-0.5, 2);
  await expect(page.locator('#tlWaveEmpty')).toBeHidden();
  await expect.poll(() => page.locator('#tlWave').evaluate(c => (c as HTMLCanvasElement).dataset.file)).toBe('Sinus e2e.wav');
  const inked = await page.locator('#tlWave').evaluate(el => {
    const c = el as HTMLCanvasElement;
    const d = c.getContext('2d')!.getImageData(0, 0, c.width, c.height).data;
    let n = 0;
    for (let i = 3; i < d.length; i += 4) if (d[i] > 0) n++;
    return n / (c.width * c.height);
  });
  expect(inked).toBeGreaterThan(0.3); // a sine at half scale fills about half the height
  await page.screenshot({ path: 'test-results/timeline-audio.png' });

  // Décalage and Volume: sent on release, clamped by the studio, saved with the show.
  await page.locator('#tlOffset').fill('200');
  await expect.poll(async () => (await timeline()).state.audio?.offset_s).toBe(0.2);
  await expect(page.locator('#tlOffsetV')).toHaveText('+200 ms');
  await page.locator('#tlGain').fill('40');
  await expect.poll(async () => (await timeline()).state.audio?.gain).toBeCloseTo(0.4, 5);
  await expect(page.locator('#tlGainV')).toHaveText('40 %');
  t = await timeline();
  expect(t.state.length).toBeCloseTo(3.2, 5);
  const saved = JSON.parse(readFileSync(path.join(studio.dataDir, 'shows', 'Chanson e2e.json'), 'utf8'));
  expect(saved.audio).toMatchObject({ file: 'Sinus e2e.wav', offset_s: 0.2, duration_s: 3 });
  expect(saved.audio.gain).toBeCloseTo(0.4, 5);
  // The offset moves the waveform: nothing before 0.2 s.
  const shifted = await studio.get<{ max: number[] }>('/api/timeline/waveform?from=0&to=0.2&px=2');
  expect(shifted.max).toEqual([0, 0]);

  // Play: the playhead runs (system clock here) and the laser stays disarmed.
  await page.locator('#tlPlay').click();
  await expect.poll(async () => (await timeline()).state.position).toBeGreaterThan(0.3);
  expect((await studio.state()).armed).toBe(false);
  await page.locator('#tlPause').click();
  await expect.poll(async () => (await timeline()).state.playing).toBe(false);
  // Click in the middle of the waveform: seek.
  const box = (await page.locator('#tlWaveBox').boundingBox())!;
  await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
  await expect.poll(async () => (await timeline()).state.position).toBeCloseTo(1.6, 1);
  await page.locator('#tlStop').click();

  // Reloading the show brings the song back; « Aucun morceau » removes it.
  await page.locator('#tlShow').selectOption('');
  await page.locator('#tlShow').selectOption('Chanson e2e');
  await expect(page.locator('#tlSong')).toHaveValue('Sinus e2e.wav');
  await page.locator('#tlSong').selectOption('');
  await expect.poll(async () => (await timeline()).state.audio).toBeNull();
  await expect(page.locator('#tlWaveEmpty')).toBeVisible();
  expect((await timeline()).state.length).toBe(2);
  // Picking it again from the library (no new import).
  await page.locator('#tlSong').selectOption('Sinus e2e.wav');
  await expect.poll(async () => (await timeline()).state.audio?.file).toBe('Sinus e2e.wav');
});

test('a damaged or unknown file is refused with a clear message', async ({ page }) => {
  await page.locator('#tlShow').selectOption('Chanson e2e');
  await expect.poll(async () => (await timeline()).state.name).toBe('Chanson e2e');
  const before = await studio.get<{ files: { file: string }[] }>('/api/media/audio');

  const broken = Buffer.concat([sineWav(1, 0.5).subarray(0, 44), Buffer.from('pas du son')]);
  broken.writeUInt32LE(4, 16); // a fmt chunk too short to be a WAV header
  await page.locator('#tlImportFile').setInputFiles({ name: 'Abîmé.wav', mimeType: 'audio/wav', buffer: broken });
  await expect(page.locator('#tlMsg')).toContainText('Import refusé');
  await expect(page.locator('#tlMsg')).toContainText('WAV illisible');

  await page.locator('#tlImportFile').setInputFiles({ name: 'faux.mp3', mimeType: 'audio/mpeg', buffer: Buffer.from('ceci n’est pas un mp3') });
  await expect(page.locator('#tlMsg')).toContainText('format audio non reconnu');

  await page.locator('#tlImportFile').setInputFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('bonjour') });
  await expect(page.locator('#tlMsg')).toContainText('extension .txt non gérée');

  // Nothing written, the show unchanged, the studio fine.
  expect(await studio.get('/api/media/audio')).toEqual(before);
  expect(existsSync(path.join(studio.dataDir, 'media', 'audio', 'Abîmé.wav'))).toBe(false);
  expect((await timeline()).state.name).toBe('Chanson e2e');
  expect((await studio.state()).armed).toBe(false);
});

test('names are confined to the media folder; a Temps show takes no song', async ({ page }) => {
  // A path in the name keeps only the file name, inside media/audio/.
  const r = await fetch(`${studio.url}/api/media/audio?name=${encodeURIComponent('../../../Evasion.wav')}`, { method: 'POST', body: sineWav(0.5, 0.2) });
  expect(r.status).toBe(200);
  expect((await r.json()).file).toBe('Evasion.wav');
  expect(existsSync(path.join(studio.dataDir, 'media', 'audio', 'Evasion.wav'))).toBe(true);
  expect(existsSync(path.join(studio.dataDir, '..', 'Evasion.wav'))).toBe(false);
  expect((await fetch(`${studio.url}/api/timeline/waveform?file=${encodeURIComponent('../shows/Chanson e2e.json')}`)).status).toBe(404);

  // A Temps (beats) show: the song picker is off, and the API says why.
  await page.locator('#tlShow').selectOption('Phrase e2e');
  await expect.poll(async () => (await timeline()).state.name).toBe('Phrase e2e');
  await expect(page.locator('#tlSong')).toBeDisabled();
  expect(await studio.post('/api/timeline/audio', { file: 'Evasion.wav' })).toBe(400);

  // Import without a Secondes show: kept in the library, attached later.
  await page.locator('#tlImportFile').setInputFiles({ name: 'Plus tard.wav', mimeType: 'audio/wav', buffer: sineWav(0.5, 0.3) });
  await expect(page.locator('#tlMsg')).toContainText('importé : chargez un show en secondes');
  const files = (await studio.get<{ files: { file: string }[] }>('/api/media/audio')).files.map(f => f.file);
  expect(files).toContain('Plus tard.wav');
});
