M48
; DRILL file {KiCad 8.0.9} date 2026-09-19T11:01:35+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-19T11:01:35+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X3.5Y-3.5
X3.5Y-52.5
X61.5Y-3.5
X61.5Y-52.5
T2
X48.105Y-34.35
X59.535Y-34.35
M30
